title: "Mine in Abyss Wiki"
url: "https://wiki.mineinabyss.com"

remote_theme: pmarsceill/just-the-docs
#color_scheme: "dark"
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/
