title: "Mine in Abyss Wiki"
url: "https://wiki.mineinabyss.com"
logo: "/assets/logo.png"
color_scheme: mineinabyss

remote_theme: pmarsceill/just-the-docs
#color_scheme: "dark"
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Footer content
# appears at the bottom of every page's main content

footer_content: "Copyright &copy; 2021 Daniel Voznyy. Distributed by an <a href=\"https://github.com/MineInAbyss/wiki/tree/master/LICENSE\">MIT license.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/MineInAbyss/wiki"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
