site_name: Mine in Abyss
site_url: https://mineinabyss.com/
repo_url: https://github.com/MineInAbyss/wiki/
theme:
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.prune
  font:
    text: Inter
    code: JetBrains Mono
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
plugins:
  - literate-nav:
      nav_file: SUMMARY.md
  - search
  - ezlinks
  - redirects:
      redirect_maps:
        contribute.md: contributing/index.md

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MineInAbyss
    - icon: fontawesome/brands/discord
      link: https://discord.gg/QXPCk2y
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MineInAbyss
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@MineInAbyss
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/MineInAbyss
